# Generated by Django 3.2.3 on 2021-05-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotesapi',
            name='author',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotesapi',
            name='quote',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quotesapi',
            name='quote_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='quotesapi',
            name='source',
            field=models.CharField(blank=True, default='Reddit', max_length=20),
        ),
    ]
