# Generated by Django 3.2.3 on 2021-05-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_quotesapi_author_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('ques', 'Question'), ('notes', 'Notes'), ('solution', 'Solution')], default='ques', max_length=10)),
                ('document', models.FileField(blank=True, null=True, upload_to='userUploaded/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='quotesapi',
            name='author_img',
            field=models.ImageField(blank=True, null=True, upload_to='quote/'),
        ),
        migrations.AlterField(
            model_name='quotesapi',
            name='quote',
            field=models.TextField(max_length=200),
        ),
    ]
