# Generated by Django 3.2.3 on 2021-05-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quespaper',
            old_name='f_name',
            new_name='fl_name',
        ),
        migrations.AlterField(
            model_name='quespaper',
            name='sub_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
