# Generated by Django 3.2.3 on 2021-05-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210518_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quespaper',
            name='semster',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='quespaper',
            name='sub_name',
            field=models.CharField(max_length=20),
        ),
    ]
