# Generated by Django 3.2.3 on 2021-05-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210518_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subjects',
            new_name='sub_names',
        ),
    ]
