# Generated by Django 3.2.3 on 2021-05-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_semster_quespaper_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quespaper',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
