# Generated by Django 3.2.3 on 2021-05-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_quespaper_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesPaperMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_date', models.DateField()),
                ('q_paper', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='quespaper',
            name='fl_name',
            field=models.CharField(max_length=100),
        ),
    ]
