# Generated by Django 3.2.3 on 2021-05-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_q_paper_quespapermedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quespapermedia',
            name='fl_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
