# Generated by Django 3.2.3 on 2021-05-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='type',
            field=models.CharField(choices=[('ques', 'Question'), ('notes', 'Notes'), ('solution', 'Solution')], default='ques', max_length=10),
        ),
    ]
