# Generated by Django 3.2.3 on 2021-05-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_quotesapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuotesApi',
        ),
    ]
