# Generated by Django 3.2.3 on 2021-05-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_quotesapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
